window.COMRADESOKO_INSTITUTIONS = [
  {
    group: "Public Universities",
    items: [
      ["Alupe University", "alupe university"],
      ["Chuka University", "chuka university"],
      ["Co-operative University of Kenya", "cooperative university of kenya"],
      ["Dedan Kimathi University of Technology", "dedan kimathi university of technology"],
      ["Egerton University", "egerton university"],
      ["Garissa University", "garissa university"],
      ["Jaramogi Oginga Odinga University of Science and Technology", "jooust"],
      ["Jomo Kenyatta University of Agriculture and Technology (JKUAT)", "jkuat"],
      ["Kaimosi Friends University", "kaimosi friends university"],
      ["Karatina University", "karatina university"],
      ["Kenyatta University", "kenyatta university"],
      ["National Defence University-Kenya", "national defence university kenya"],
      ["Kibabii University", "kibabii university"],
      ["Kirinyaga University", "kirinyaga university"],
      ["Kisii University", "kisii university"],
      ["Laikipia University", "laikipia university"],
      ["Machakos University", "machakos university"],
      ["Maasai Mara University", "maasai mara university"],
      ["Maseno University", "maseno university"],
      ["Masinde Muliro University of Science and Technology", "masinde muliro university"],
      ["Meru University of Science and Technology", "meru university of science and technology"],
      ["Moi University", "moi university"],
      ["Murang'a University of Technology", "muranga university of technology"],
      ["Open University of Kenya", "open university of kenya"],
      ["Pwani University", "pwani university"],
      ["Rongo University", "rongo university"],
      ["South Eastern Kenya University", "south eastern kenya university"],
      ["Taita Taveta University", "taita taveta university"],
      ["Technical University of Kenya", "technical university of kenya"],
      ["Technical University of Mombasa", "technical university of mombasa"],
      ["Tharaka University", "tharaka university"],
      ["Tom Mboya University", "tom mboya university"],
      ["University of Eldoret", "university of eldoret"],
      ["University of Embu", "university of embu"],
      ["University of Kabianga", "university of kabianga"],
      ["University of Nairobi", "university of nairobi"]
    ]
  },
  {
    group: "Private Universities",
    items: [
      ["Adventist University of Africa", "adventist university of africa"],
      ["Africa International University", "africa international university"],
      ["Africa Nazarene University", "africa nazarene university"],
      ["Aga Khan University", "aga khan university"],
      ["Amref International University", "amref international university"],
      ["Catholic University of Eastern Africa", "catholic university of eastern africa"],
      ["Daystar University", "daystar university"],
      ["East Africa University", "east africa university"],
      ["Gretsa University", "gretsa university"],
      ["Great Lakes University of Kisumu", "great lakes university of kisumu"],
      ["International Leadership University", "international leadership university"],
      ["Islamic University of Kenya", "islamic university of kenya"],
      ["Kabarak University", "kabarak university"],
      ["KAG East University", "kag east university"],
      ["KCA University", "kca university"],
      ["Kenya Highlands Evangelical University", "kenya highlands evangelical university"],
      ["Kenya Methodist University", "kenya methodist university"],
      ["Kiriri Women's University of Science and Technology", "kiriri womens university"],
      ["Lukenya University", "lukenya university"],
      ["Management University of Africa", "management university of africa"],
      ["Mount Kenya University", "mount kenya university"],
      ["Pan Africa Christian University", "pan africa christian university"],
      ["Pioneer International University", "pioneer international university"],
      ["Presbyterian University of East Africa", "presbyterian university of east africa"],
      ["Riara University", "riara university"],
      ["Scott Christian University", "scott christian university"],
      ["St. Paul's University", "st pauls university"],
      ["Strathmore University", "strathmore university"],
      ["Tangaza University", "tangaza university"],
      ["Umma University", "umma university"],
      ["United States International University-Africa (USIU-Africa)", "usiu africa"],
      ["University of Eastern Africa, Baraton", "university of eastern africa baraton"],
      ["Uzima University", "uzima university"],
      ["Zetech University", "zetech university"]
    ]
  },
  {
    group: "University Colleges and Major National Colleges",
    items: [
      ["Bomet University College", "bomet university college"],
      ["Hekima University College", "hekima university college"],
      ["Koitalel Samoei University College", "koitalel samoei university college"],
      ["Marist International University College", "marist international university college"],
      ["Regina Pacis University College", "regina pacis university college"],
      ["Turkana University College", "turkana university college"],
      ["Bandari Maritime Academy", "bandari maritime academy"],
      ["Bukura Agricultural College", "bukura agricultural college"],
      ["Kenya Forestry College", "kenya forestry college"],
      ["Kenya Institute of Highways and Building Technology", "kihbt"],
      ["Kenya Institute of Mass Communication", "kenya institute of mass communication"],
      ["Kenya Institute of Special Education", "kise"],
      ["Kenya Medical Training College (KMTC)", "kmtc"],
      ["Kenya School of Government", "kenya school of government"],
      ["Kenya School of Law", "kenya school of law"],
      ["Kenya School of Monetary Studies", "kenya school of monetary studies"],
      ["Kenya Utalii College", "kenya utalii college"],
      ["Kenya Water Institute", "kenya water institute"],
      ["Kenya Wildlife Service Training Institute", "kws training institute"],
      ["Kenya Institute of Surveying and Mapping", "kism"],
      ["Railway Training Institute", "railway training institute"]
    ]
  }
];
